name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install babel plugin
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Install TypeScript and parser
      run: npm install --save-dev typescript @typescript-eslint/parser

    - name: Run linter
      run: npm run lint
